#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import division
import sys

BYTES_COUNT = 256
CHUNK_SIZE = 1024*64
OUT_FILENAME = sys.argv[1]

freqs = [0] * BYTES_COUNT
total = 0

def read_in_chunks(infile, chunk_size=CHUNK_SIZE):
    chunk = infile.read(chunk_size)
    while chunk:
        yield chunk
        chunk = infile.read(chunk_size)

for name in sys.argv[2:]:
    print("reading file: "+name)
    with open(name, "rb") as f:
        for chunk in bytearray(read_in_chunks(f)):
            total += len(chunk)
            for byte in chunk:
                freqs[byte] += 1

print(total)
with open(OUT_FILENAME, "w+") as f:
    for b in freqs:
        f.write("%f\n" % (b / total))

